#+TITLE:       Thriving vs Surviving
#+AUTHOR:      Yusaira Khan
#+EMAIL:       yusairamkhan@gmail.com
#+DATE:        2021-03-07 Sun
#+URI:         /blog/%y/%m/%d/thriving-vs-surviving
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        <TODO: insert your tags here>
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Thriving is hard, surviving is hard
#+TWEETID:     1369085615296442380

I was thinking about Thriving and Surviving. And about Community and Individualism. Obedience and Disobience.


Animals survive. Just live to eat, sleep and bear children. Eat to live, live to eat.


Machines survive. Always outputting things. not bound by the limits of the flesh.


We, as humans, both survive and thrive.  We are limited by the flesh, but we don't have to just survive. We can do more than survive. We can have creative output. We can thrive. But we can't always thrive, like machines can. We are limited by our flesh.

We also have to balance our lives. Thrive we have managed to survive to a good degree. Stop thriving and focus on surviving, when survival is hard.

To do this, we can do it in a Community, or as Indivuals.

Communities can help its members a lot. But there is an aspect of obedience involved. If we disobey, we can be ostracized from our communities. And sometimes, having strong individual thoughts can be seen as disobedience. I see it a lot in the South Asian communities I come from.

Indivualism is  pretty great. Its really freeing. But it can get lonely, and hard. life is really hard. I feel it a lot in my current life in North America. 

Sometimes I get very disoriented by these dichotomies. Surviving and Thriving. Indivualism and Community. South Asia and North America. Different friends, family, over the years say different things. Its hard for me to balance if i've been stagnant, not thriving too long, just vegetating. or if i've focused too hard on thriving and my physical and mental health is ignored. If i should listen to the communities i belonged to. or if i should pay attention to the individual voice that my communities reject.

A lot of these musings and vocabulary comes from Rolo May's Man's Search for Himself.

My Therapist helped me realize that my sense of self, which is helpful when orienting, is suppressed.  Like the alien race in Douglas Adams' Mostly Harmless. Where the part of the alien race that was supposed to figure out what was wrong, got hit by an asteroid and fell out of their spaceship. The backup for that module fell throught the whole left by the asteroid.

My coach helped me realize that i am not very fluent in thriving. 

I am very grateful the people in my life. and myself.

