#+TITLE:       I have a crush on Linguistics
#+AUTHOR:      Yusaira Khan
#+EMAIL:       yusairamkhan@gmail.com
#+DATE:        2020-06-12 Fri
#+URI:         /blog/%y/%m/%d/i-have-a-crush-on-linguistics
#+KEYWORDS:    linguistics
#+TAGS:        linguistics
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

I've been obsessed with the etymology of words in English that relate to words in Bengali/Hindi for forever.
English is a Germanic (and a bit of Latin derived) language. Bengali is a Sanskrit derived language. Sanskrit and Latin are thought to derived from Proto-Indo-European.

Proto Indo-European (PIE)  language has many reconstructed words from its descendants. 
Descendant languages include: English, German, other Germanic languages
French, Spanish, other romance languages
Russian
Greek
Persian
Bengali, Hindi, Urdu, other Sanskrit derived languages

Words that are common between English, Bengali and PIE are (amazingly) words that were used in everyday life by people thousands of years ago. This is my favourite video about it

One of the first words I found out were related are: 
Summer (English)
সন (Shon) (Bengali for year)
संवत (Hindi for year)

Related words:
Young (English)
 (Jowan) (Persian for young) جوان
জোয়ান (Jo-ahn) (Bengali for young man)
जवान (Javan) 
